// <auto-generated />
using System;
using HexMaster.ThePrey.Games.Data.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HexMaster.ThePrey.Games.Data.Postgres.Migrations
{
    [DbContext(typeof(GamesDbContext))]
    [Migration("20260604112252_AddGameCode")]
    partial class AddGameCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HexMaster.ThePrey.Games.DomainModels.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("GameCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayfieldId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("GameCode")
                        .IsUnique();

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("HexMaster.ThePrey.Games.DomainModels.Game", b =>
                {
                    b.OwnsOne("HexMaster.ThePrey.Games.DomainModels.GameConfiguration", "Configuration", b1 =>
                        {
                            b1.Property<Guid>("GameId")
                                .HasColumnType("uuid");

                            b1.Property<int>("DefaultLocationInterval")
                                .HasColumnType("integer")
                                .HasColumnName("DefaultLocationInterval");

                            b1.Property<bool>("EnableHunterBoundaryPenalty")
                                .HasColumnType("boolean")
                                .HasColumnName("EnableHunterBoundaryPenalty");

                            b1.Property<bool>("EnablePreyBoundaryPenalties")
                                .HasColumnType("boolean")
                                .HasColumnName("EnablePreyBoundaryPenalties");

                            b1.Property<int>("FinalLocationInterval")
                                .HasColumnType("integer")
                                .HasColumnName("FinalLocationInterval");

                            b1.Property<int>("FinalStageDuration")
                                .HasColumnType("integer")
                                .HasColumnName("FinalStageDuration");

                            b1.Property<int>("GameDuration")
                                .HasColumnType("integer")
                                .HasColumnName("GameDuration");

                            b1.Property<int>("HunterDelayTime")
                                .HasColumnType("integer")
                                .HasColumnName("HunterDelayTime");

                            b1.HasKey("GameId");

                            b1.ToTable("Games");

                            b1.WithOwner()
                                .HasForeignKey("GameId");
                        });

                    b.OwnsMany("HexMaster.ThePrey.Games.DomainModels.GameParticipant", "_participants", b1 =>
                        {
                            b1.Property<Guid>("GameId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("UserId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");

                            b1.Property<string>("_locations")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("Locations");

                            b1.Property<string>("_penalties")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("Penalties");

                            b1.HasKey("GameId", "UserId");

                            b1.ToTable("GameParticipants", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GameId");

                            b1.OwnsOne("HexMaster.ThePrey.Games.DomainModels.GpsCoordinate", "Location", b2 =>
                                {
                                    b2.Property<Guid>("GameParticipantGameId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("GameParticipantUserId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("Latitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("Longitude");

                                    b2.HasKey("GameParticipantGameId", "GameParticipantUserId");

                                    b2.ToTable("GameParticipants");

                                    b2.WithOwner()
                                        .HasForeignKey("GameParticipantGameId", "GameParticipantUserId");
                                });

                            b1.Navigation("Location");
                        });

                    b.OwnsMany("HexMaster.ThePrey.Games.DomainModels.LobbyPlayer", "Lobby", b1 =>
                        {
                            b1.Property<Guid>("GameId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("UserId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("ProfilePictureUrl")
                                .HasColumnType("text");

                            b1.HasKey("GameId", "UserId");

                            b1.ToTable("LobbyPlayers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GameId");
                        });

                    b.Navigation("Configuration")
                        .IsRequired();

                    b.Navigation("Lobby");

                    b.Navigation("_participants");
                });
#pragma warning restore 612, 618
        }
    }
}
